"""initial schema

Revision ID: 826cbe957337
Revises: 
Create Date: 2026-08-28 12:37:04.054595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826cbe957337'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('asset_class', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instruments.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', name='uq_candle_identity')
    )
    op.create_index(op.f('ix_candles_symbol'), 'candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_candles_timeframe'), 'candles', ['timeframe'], unique=False)
    op.create_index(op.f('ix_candles_timestamp'), 'candles', ['timestamp'], unique=False)
    op.create_table('daily_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('opening_price', sa.Float(), nullable=False),
    sa.Column('opening_day_high', sa.Float(), nullable=False),
    sa.Column('opening_day_low', sa.Float(), nullable=False),
    sa.Column('previous_day_high', sa.Float(), nullable=True),
    sa.Column('previous_day_low', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['instruments.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_levels_symbol'), 'daily_levels', ['symbol'], unique=False)
    op.create_index(op.f('ix_daily_levels_trading_date'), 'daily_levels', ['trading_date'], unique=False)
    op.create_table('fair_value_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('upper', sa.Float(), nullable=False),
    sa.Column('lower', sa.Float(), nullable=False),
    sa.Column('mitigated_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instruments.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'created_at', 'direction', name='uq_fair_value_gap_identity')
    )
    op.create_index(op.f('ix_fair_value_gaps_created_at'), 'fair_value_gaps', ['created_at'], unique=False)
    op.create_index(op.f('ix_fair_value_gaps_symbol'), 'fair_value_gaps', ['symbol'], unique=False)
    op.create_index(op.f('ix_fair_value_gaps_timeframe'), 'fair_value_gaps', ['timeframe'], unique=False)
    op.create_table('liquidity_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('formed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instruments.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'label', 'formed_at', name='uq_liquidity_level_identity')
    )
    op.create_index(op.f('ix_liquidity_levels_formed_at'), 'liquidity_levels', ['formed_at'], unique=False)
    op.create_index(op.f('ix_liquidity_levels_symbol'), 'liquidity_levels', ['symbol'], unique=False)
    op.create_index(op.f('ix_liquidity_levels_timeframe'), 'liquidity_levels', ['timeframe'], unique=False)
    op.create_table('market_structure_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('broken_level', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instruments.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', 'event_type', name='uq_structure_event_identity')
    )
    op.create_index(op.f('ix_market_structure_events_symbol'), 'market_structure_events', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_structure_events_timeframe'), 'market_structure_events', ['timeframe'], unique=False)
    op.create_index(op.f('ix_market_structure_events_timestamp'), 'market_structure_events', ['timestamp'], unique=False)
    op.create_table('order_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('zone_low', sa.Float(), nullable=False),
    sa.Column('zone_high', sa.Float(), nullable=False),
    sa.Column('structure_event_type', sa.String(length=8), nullable=False),
    sa.Column('mitigated', sa.Boolean(), nullable=False),
    sa.Column('mitigated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retest_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instruments.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'created_at', 'direction', name='uq_order_block_identity')
    )
    op.create_index(op.f('ix_order_blocks_created_at'), 'order_blocks', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_blocks_symbol'), 'order_blocks', ['symbol'], unique=False)
    op.create_index(op.f('ix_order_blocks_timeframe'), 'order_blocks', ['timeframe'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('session_name', sa.String(length=16), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('session_open', sa.Float(), nullable=False),
    sa.Column('session_high', sa.Float(), nullable=False),
    sa.Column('session_low', sa.Float(), nullable=False),
    sa.Column('session_close', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instruments.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_symbol'), 'sessions', ['symbol'], unique=False)
    op.create_index(op.f('ix_sessions_trading_date'), 'sessions', ['trading_date'], unique=False)
    op.create_table('swing_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=4), nullable=False),
    sa.Column('label', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instruments.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', 'kind', name='uq_swing_point_identity')
    )
    op.create_index(op.f('ix_swing_points_symbol'), 'swing_points', ['symbol'], unique=False)
    op.create_index(op.f('ix_swing_points_timeframe'), 'swing_points', ['timeframe'], unique=False)
    op.create_index(op.f('ix_swing_points_timestamp'), 'swing_points', ['timestamp'], unique=False)
    op.create_table('liquidity_sweeps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liquidity_level_id', sa.Integer(), nullable=False),
    sa.Column('swept_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sweep_extreme', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['liquidity_level_id'], ['liquidity_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('liquidity_level_id', 'swept_at', name='uq_liquidity_sweep_identity')
    )
    op.create_index(op.f('ix_liquidity_sweeps_liquidity_level_id'), 'liquidity_sweeps', ['liquidity_level_id'], unique=False)
    op.create_index(op.f('ix_liquidity_sweeps_swept_at'), 'liquidity_sweeps', ['swept_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_liquidity_sweeps_swept_at'), table_name='liquidity_sweeps')
    op.drop_index(op.f('ix_liquidity_sweeps_liquidity_level_id'), table_name='liquidity_sweeps')
    op.drop_table('liquidity_sweeps')
    op.drop_index(op.f('ix_swing_points_timestamp'), table_name='swing_points')
    op.drop_index(op.f('ix_swing_points_timeframe'), table_name='swing_points')
    op.drop_index(op.f('ix_swing_points_symbol'), table_name='swing_points')
    op.drop_table('swing_points')
    op.drop_index(op.f('ix_sessions_trading_date'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_symbol'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_order_blocks_timeframe'), table_name='order_blocks')
    op.drop_index(op.f('ix_order_blocks_symbol'), table_name='order_blocks')
    op.drop_index(op.f('ix_order_blocks_created_at'), table_name='order_blocks')
    op.drop_table('order_blocks')
    op.drop_index(op.f('ix_market_structure_events_timestamp'), table_name='market_structure_events')
    op.drop_index(op.f('ix_market_structure_events_timeframe'), table_name='market_structure_events')
    op.drop_index(op.f('ix_market_structure_events_symbol'), table_name='market_structure_events')
    op.drop_table('market_structure_events')
    op.drop_index(op.f('ix_liquidity_levels_timeframe'), table_name='liquidity_levels')
    op.drop_index(op.f('ix_liquidity_levels_symbol'), table_name='liquidity_levels')
    op.drop_index(op.f('ix_liquidity_levels_formed_at'), table_name='liquidity_levels')
    op.drop_table('liquidity_levels')
    op.drop_index(op.f('ix_fair_value_gaps_timeframe'), table_name='fair_value_gaps')
    op.drop_index(op.f('ix_fair_value_gaps_symbol'), table_name='fair_value_gaps')
    op.drop_index(op.f('ix_fair_value_gaps_created_at'), table_name='fair_value_gaps')
    op.drop_table('fair_value_gaps')
    op.drop_index(op.f('ix_daily_levels_trading_date'), table_name='daily_levels')
    op.drop_index(op.f('ix_daily_levels_symbol'), table_name='daily_levels')
    op.drop_table('daily_levels')
    op.drop_index(op.f('ix_candles_timestamp'), table_name='candles')
    op.drop_index(op.f('ix_candles_timeframe'), table_name='candles')
    op.drop_index(op.f('ix_candles_symbol'), table_name='candles')
    op.drop_table('candles')
    op.drop_table('instruments')
    # ### end Alembic commands ###
